### ISSUE TITLE
Allow sharing of text with PocketPlan => Import as new Note

### ISSUE THREAD

**Issue by pipiscrew** [estep248/PocketPlan#33]
hi all,

testing v1.3.4, but wait, the application does not appear to SHARE menu.. 

example, select text on any other application and press SHARE.. 

can you add the application there  ??

`you need to declare intent listeners in your android manifest`

**Comment by JakeGonder** [comment]
What device / Android version are you on? I tested it, and it worked. What i did:

Open a note => select text 

![grafik](https://user-images.githubusercontent.com/51212295/161977540-21f21a9c-b2ba-44fc-b814-5f093f0fa07e.png)

select more options

![grafik](https://user-images.githubusercontent.com/51212295/161977572-764cf639-6fd9-480d-90fb-866eeab3a43e.png)

select share

![grafik](https://user-images.githubusercontent.com/51212295/161977594-e9ac0c3c-b290-482e-aaeb-91cb3c1b9ba1.png)

**Comment by pipiscrew** [comment]
hi @JakeGonder 

Im talking about the **opposite**, to be on SMS or a website and send a note to **PocketPlan**

**Comment by JakeGonder** [comment]
Oh now i understand, sounds like a good idea, we will try to add this.

**Comment by JakeGonder** [comment]
Added the feature on the beta branch

**Comment by JakeGonder** [comment]
The feature is now live in 1.3.5
