### ISSUE TITLE
[Feature Req] Show app usage time on home screen

### ISSUE THREAD

**Issue by Bugaddr** [estep248/PocketPlan#37]
An option to show "daily app usage time" for top 3 apps along with "total screen time" can be added on the home tab as an extra tool for productivity. I feel that this will not affect the current appearance of home tab. Thanks :)

**Comment by JakeGonder** [comment]
We definetly see the possibility for adding more elements to the home panel, however we plan to fill this with a calendar module. Additionally this feature would require new permissions (access to app usage data) and we want to keep the required permissions as minimal as possible. This also would just reflect data that can already be viewed through different channels, while PocketPlan focuses on data that you enter into the app yourself.

**Comment by Bugaddr** [comment]
Sounds valid, calender feels like much better option. Thanks
